### PR TITLE
Removing Json.NET dependency

### PR DESCRIPTION
**Pull request by RichardVasquez**
I had a bit of concern regarding the JsonProperty attributes used with Json.NET, so to maintain compatibility with the JSON fields, I snake cased the properties on the serializable fields to maintain consistency.

### CODE REVIEW

**Comment by RichardVasquez** [comment]
Ok, just so we're on the same page here, and since it's a small enough example, something like this?

```c#
    [Serializable]
    public class KongregateUserItem
    {
        [SerializeField]
        private readonly int id;
        public readonly int Id { get => id; }

        [SerializeField]         
        private readonly string identifier;
        public readonly string Identifier { get => identifier; }

        [SerializeField]
        private readonly string data;
        public readonly string Data { get => data; }

        [SerializeField]
        private readonly int remaining_uses;
        public readonly int RemainingUses { get => remaining_uses; }
    }
```

**Comment by randomPoison** [comment]
That's correct! I'd also suggest using the simplified getter syntax, since it'll make the properties very terse to declare:

```
[SerializeField]
private readonly int remaining_uses;
public readonly int RemainingUses => remaining_uses;
```

**Comment by randomPoison** [comment]
Now that I think about it, this would be a good thing to add some unit tests for. In theory this change shouldn't break anything, but on the off chance that there's something I'm misunderstanding about Unity's serialization that would cause this to not work, it'd be good to have unit tests confirming the expected behavior.

Is that something you'd be comfortable adding? I realize it increases the work involved, so I totally understand if not! I'll just want to put those together myself before merging 🙂

**Comment by RichardVasquez** [comment]
In this specific case, I'm going to have to hand off the unit tests to you.  Many other things on my plate.

I'll work on the serialization as above along with the getter syntax you mentioned.  I'm on the U.S. west coast, so that'll affect my PR times in the upcoming evenings, but I'll get that to you as soon as I've got some free time.

**Comment by RichardVasquez** [comment]
Tweaked as above for both classes.

**Comment by randomPoison** [comment]
It looks like `JsonUtility.FromJson()` doesn't actually support deserializing an array directly, it'll only work with objects. This can still be worked around, but is going to require further changes. I'm going to close this PR for now, and open a new one that includes the necessary changes and unit tests. Your original commits will be included in the new PR once it's opened, though.

Thanks again for the contributions!

**Pull request closed without merging**
